
env = Environment(
    CXXFLAGS='-m64 -pipe -O3 -g -Wall -W -Wextra -Wno-attributes -Wno-unused-parameter -Wno-unknown-pragmas -std=c++11',
    LINKFLAGS=['-m64', '-g', '-Wl,-O3'],
    CPPPATH=['#../../../include'],
    LIBPATH=['.', '#../../../bin.gtk/x64'],
    LIBS=['dl', 'sciter-gtk', 'sqlite3']
)

env.ParseConfig("pkg-config gtk+-3.0 --cflags --libs")
env.SharedLibrary('tiscript-sqlite', Glob('*.cpp'), LIBPREFIX='')

Clean('all', '.sconsign.dblite')
