
env = Environment(
    CXXFLAGS='-m64 -pipe -O3 -g -Wall -W -Wextra -Wno-attributes -Wno-unused-parameter -Wno-unknown-pragmas -std=c++11',
    LINKFLAGS=['-m64', '-g', '-Wl,-O3'],
    CPPPATH=['#../../include'],
    LIBPATH=['#../../bin.gtk/x64'],
    LIBS=['dl', 'sciter-gtk']
)

env.ParseConfig("pkg-config gtk+-3.0 --cflags --libs")
env.Program('notes', ['notes.cpp', 'resources.cpp'])

Clean('all', '.sconsign.dblite')
